### ISSUE TITLE
remove console.log in app.js

### ISSUE THREAD

**Issue by paolourciullo** [paolourciullo/FCC-personal-portfolio#10]
james cox, basically the human version of this dog here 👇
![image](https://user-images.githubusercontent.com/67667160/121919740-52a4e180-cd05-11eb-9d7c-a46892110d64.png)
said to fix this.  he was super nice about it though.
remove console.log from app.js for cryin out loud
![image](https://user-images.githubusercontent.com/67667160/121920004-9697e680-cd05-11eb-980d-d137f2d31c45.png)

**Comment by KeenanJones1** [comment]
I'll like to work on this. Do you want to remove the for loop as well?

**Comment by paolourciullo** [comment]
yeah, that would be great!  thanks so much!  

-paolo
